# Generated by Django 3.1.7 on 2021-03-03 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0002_auto_20210304_0004'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='added_date',
            new_name='added_on',
        ),
    ]
