# Generated by Django 3.1.7 on 2021-03-03 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_auto_20210304_0008'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='updated_on',
            new_name='added_date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='added_on',
        ),
    ]
